# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodCad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('cod_fab', models.CharField(max_length=10, verbose_name='SKU Fabricante')),
                ('cod_int', models.CharField(max_length=10, verbose_name='Código Interno')),
                ('cat', models.CharField(max_length=15, verbose_name='Categorias')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('desc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('preco', models.CharField(max_length=10, verbose_name='Preço')),
                ('cor', models.CharField(max_length=10, verbose_name='Cor da Página')),
            ],
        ),
    ]
