# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-11 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180810_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
