# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20180811_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcad',
            name='cat',
            field=models.CharField(max_length=55, verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cod_fab',
            field=models.CharField(max_length=20, verbose_name='SKU Fabricante'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cod_int',
            field=models.CharField(max_length=20, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='preco',
            field=models.CharField(max_length=20, verbose_name='Preço'),
        ),
    ]
