# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20180817_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcad',
            name='cat',
            field=models.CharField(max_length=100, verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cod_fab',
            field=models.CharField(max_length=100, verbose_name='SKU Fabricante'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cod_int',
            field=models.CharField(max_length=200, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cor',
            field=models.CharField(max_length=100, verbose_name='Cor da Página'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='modelo',
            field=models.CharField(max_length=500, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='preco',
            field=models.CharField(max_length=200, verbose_name='Preço'),
        ),
    ]
