# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20180817_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcad',
            name='marcabusca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca interna'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cod_fab',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU Fabricante'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cod_int',
            field=models.CharField(blank=True, max_length=200, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='cor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cor da Página'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='modelo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='prodcad',
            name='preco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Preço'),
        ),
    ]
